//
// CartaoResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CartaoResponse: JSONEncodable {

    public var dataValidade: String?
    public var descricaoEstagio: String?
    public var descricaoStatus: String?
    public var estagio: Int?
    public var flagCancelamento: Bool?
    public var idCartao: Int?
    public var numeroCartao: String?
    public var portador: String?
    public var portadorId: Int?
    public var status: Int?
    public var statusData: NSDate?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["dataValidade"] = self.dataValidade
        nillableDictionary["descricaoEstagio"] = self.descricaoEstagio
        nillableDictionary["descricaoStatus"] = self.descricaoStatus
        nillableDictionary["estagio"] = self.estagio
        nillableDictionary["flagCancelamento"] = self.flagCancelamento
        nillableDictionary["idCartao"] = self.idCartao
        nillableDictionary["numeroCartao"] = self.numeroCartao
        nillableDictionary["portador"] = self.portador
        nillableDictionary["portadorId"] = self.portadorId
        nillableDictionary["status"] = self.status
        nillableDictionary["statusData"] = self.statusData?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
