//
// GlobaltagavisoviagemAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class GlobaltagavisoviagemAPI: APIBase {
    /**
     
     {{{aviso_viagem_resource_consultar}}}
     
     - parameter id: (path) {{{aviso_viagem_resource_consultar_param_id}}} 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func consultarUsingGET8(id id: Int, completion: ((data: AvisoViagemResponse?, error: ErrorType?) -> Void)) {
        consultarUsingGET8WithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     {{{aviso_viagem_resource_consultar}}}
     
     - GET /api/avisos-viagens/{id}
     - {{{aviso_viagem_resource_consultar_notes}}}
     - examples: [{contentType=application/json, example={
  "idCartao" : 123456789,
  "dataFim" : "aeiou",
  "id" : 123456789,
  "dataInicio" : "aeiou",
  "flagAtivo" : 123,
  "codigoPais" : "aeiou"
}}]
     
     - parameter id: (path) {{{aviso_viagem_resource_consultar_param_id}}} 

     - returns: RequestBuilder<AvisoViagemResponse> 
     */
    public class func consultarUsingGET8WithRequestBuilder(id id: Int) -> RequestBuilder<AvisoViagemResponse> {
        var path = "/api/avisos-viagens/{id}"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = PierAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<AvisoViagemResponse>.Type = PierAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     {{{aviso_viagem_resource_desabilitar}}}
     
     - parameter id: (path) {{{aviso_viagem_resource_desabilitar_param_id}}} 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func desabilitarUsingPOST(id id: Int, completion: ((data: AvisoViagemResponse?, error: ErrorType?) -> Void)) {
        desabilitarUsingPOSTWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     {{{aviso_viagem_resource_desabilitar}}}
     
     - POST /api/avisos-viagens/{id}/desabilitar
     - {{{aviso_viagem_resource_desabilitar_notes}}}
     - examples: [{contentType=application/json, example={
  "idCartao" : 123456789,
  "dataFim" : "aeiou",
  "id" : 123456789,
  "dataInicio" : "aeiou",
  "flagAtivo" : 123,
  "codigoPais" : "aeiou"
}}]
     
     - parameter id: (path) {{{aviso_viagem_resource_desabilitar_param_id}}} 

     - returns: RequestBuilder<AvisoViagemResponse> 
     */
    public class func desabilitarUsingPOSTWithRequestBuilder(id id: Int) -> RequestBuilder<AvisoViagemResponse> {
        var path = "/api/avisos-viagens/{id}/desabilitar"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = PierAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<AvisoViagemResponse>.Type = PierAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     {{{aviso_viagem_resource_habilitar}}}
     
     - parameter id: (path) {{{aviso_viagem_resource_habilitar_param_id}}} 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func habilitarUsingPOST(id id: Int, completion: ((data: AvisoViagemResponse?, error: ErrorType?) -> Void)) {
        habilitarUsingPOSTWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     {{{aviso_viagem_resource_habilitar}}}
     
     - POST /api/avisos-viagens/{id}/habilitar
     - {{{aviso_viagem_resource_habilitar_notes}}}
     - examples: [{contentType=application/json, example={
  "idCartao" : 123456789,
  "dataFim" : "aeiou",
  "id" : 123456789,
  "dataInicio" : "aeiou",
  "flagAtivo" : 123,
  "codigoPais" : "aeiou"
}}]
     
     - parameter id: (path) {{{aviso_viagem_resource_habilitar_param_id}}} 

     - returns: RequestBuilder<AvisoViagemResponse> 
     */
    public class func habilitarUsingPOSTWithRequestBuilder(id id: Int) -> RequestBuilder<AvisoViagemResponse> {
        var path = "/api/avisos-viagens/{id}/habilitar"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = PierAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<AvisoViagemResponse>.Type = PierAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     {{{aviso_viagem_resource_listar}}}
     
     - parameter sort: (query) {{{global_menssagem_sort_sort}}} (optional)
     - parameter page: (query) {{{global_menssagem_sort_page_value}}} (optional)
     - parameter limit: (query) {{{global_menssagem_sort_limit}}} (optional)
     - parameter idCartao: (query) {{{aviso_viagem_request_id_cartao_value}}} (optional)
     - parameter codigoPais: (query) {{{aviso_viagem_request_codigo_pais_value}}} (optional)
     - parameter dataInicio: (query) {{{aviso_viagem_request_data_inicio_value}}} (optional)
     - parameter dataFim: (query) {{{aviso_viagem_request_data_fim_value}}} (optional)
     - parameter flagAtivo: (query) {{{aviso_viagem_request_flag_ativo_value}}} (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func listarUsingGET9(sort sort: [String]?, page: Int?, limit: Int?, idCartao: Int?, codigoPais: String?, dataInicio: String?, dataFim: String?, flagAtivo: Int?, completion: ((data: PageAvisoViagemResponse?, error: ErrorType?) -> Void)) {
        listarUsingGET9WithRequestBuilder(sort: sort, page: page, limit: limit, idCartao: idCartao, codigoPais: codigoPais, dataInicio: dataInicio, dataFim: dataFim, flagAtivo: flagAtivo).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     {{{aviso_viagem_resource_listar}}}
     
     - GET /api/avisos-viagens
     - {{{aviso_viagem_resource_listar_notes}}}
     - examples: [{contentType=application/json, example={
  "previousPage" : 123,
  "last" : true,
  "hasContent" : true,
  "hasNextPage" : true,
  "nextPage" : 123,
  "content" : [ {
    "idCartao" : 123456789,
    "dataFim" : "aeiou",
    "id" : 123456789,
    "dataInicio" : "aeiou",
    "flagAtivo" : 123,
    "codigoPais" : "aeiou"
  } ],
  "totalElements" : 123456789,
  "number" : 123,
  "firstPage" : true,
  "numberOfElements" : 123,
  "size" : 123,
  "totalPages" : 123,
  "hasPreviousPage" : true,
  "first" : true
}}]
     
     - parameter sort: (query) {{{global_menssagem_sort_sort}}} (optional)
     - parameter page: (query) {{{global_menssagem_sort_page_value}}} (optional)
     - parameter limit: (query) {{{global_menssagem_sort_limit}}} (optional)
     - parameter idCartao: (query) {{{aviso_viagem_request_id_cartao_value}}} (optional)
     - parameter codigoPais: (query) {{{aviso_viagem_request_codigo_pais_value}}} (optional)
     - parameter dataInicio: (query) {{{aviso_viagem_request_data_inicio_value}}} (optional)
     - parameter dataFim: (query) {{{aviso_viagem_request_data_fim_value}}} (optional)
     - parameter flagAtivo: (query) {{{aviso_viagem_request_flag_ativo_value}}} (optional)

     - returns: RequestBuilder<PageAvisoViagemResponse> 
     */
    public class func listarUsingGET9WithRequestBuilder(sort sort: [String]?, page: Int?, limit: Int?, idCartao: Int?, codigoPais: String?, dataInicio: String?, dataFim: String?, flagAtivo: Int?) -> RequestBuilder<PageAvisoViagemResponse> {
        let path = "/api/avisos-viagens"
        let URLString = PierAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [
            "sort": sort,
            "page": page,
            "limit": limit,
            "idCartao": idCartao,
            "codigoPais": codigoPais,
            "dataInicio": dataInicio,
            "dataFim": dataFim,
            "flagAtivo": flagAtivo
        ]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<PageAvisoViagemResponse>.Type = PierAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
    }

    /**
     
     {{{aviso_viagem_resource_salvar}}}
     
     - parameter idCartao: (query) {{{aviso_viagem_persist_id_cartao_value}}} 
     - parameter codigoPais: (query) {{{aviso_viagem_persist_codigo_pais_value}}} 
     - parameter dataInicio: (query) {{{aviso_viagem_persist_data_inicio_value}}} 
     - parameter dataFim: (query) {{{aviso_viagem_persist_data_fim_value}}} 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func salvarUsingPOST3(idCartao idCartao: Int, codigoPais: String, dataInicio: String, dataFim: String, completion: ((data: AvisoViagemResponse?, error: ErrorType?) -> Void)) {
        salvarUsingPOST3WithRequestBuilder(idCartao: idCartao, codigoPais: codigoPais, dataInicio: dataInicio, dataFim: dataFim).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     {{{aviso_viagem_resource_salvar}}}
     
     - POST /api/avisos-viagens
     - {{{aviso_viagem_resource_salvar_notes}}}
     - examples: [{contentType=application/json, example={
  "idCartao" : 123456789,
  "dataFim" : "aeiou",
  "id" : 123456789,
  "dataInicio" : "aeiou",
  "flagAtivo" : 123,
  "codigoPais" : "aeiou"
}}]
     
     - parameter idCartao: (query) {{{aviso_viagem_persist_id_cartao_value}}} 
     - parameter codigoPais: (query) {{{aviso_viagem_persist_codigo_pais_value}}} 
     - parameter dataInicio: (query) {{{aviso_viagem_persist_data_inicio_value}}} 
     - parameter dataFim: (query) {{{aviso_viagem_persist_data_fim_value}}} 

     - returns: RequestBuilder<AvisoViagemResponse> 
     */
    public class func salvarUsingPOST3WithRequestBuilder(idCartao idCartao: Int, codigoPais: String, dataInicio: String, dataFim: String) -> RequestBuilder<AvisoViagemResponse> {
        let path = "/api/avisos-viagens"
        let URLString = PierAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [
            "idCartao": idCartao,
            "codigoPais": codigoPais,
            "dataInicio": dataInicio,
            "dataFim": dataFim
        ]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<AvisoViagemResponse>.Type = PierAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: false)
    }

}
