//
// GlobaltagtokenAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class GlobaltagtokenAPI: APIBase {
    /**
     
     {{{token_resource_callback}}}
     
     - parameter bodyAccessToken: (body) bodyAccessToken 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func callbackUsingPOST(bodyAccessToken bodyAccessToken: BodyAccessToken, completion: ((data: BodyAccessToken?, error: ErrorType?) -> Void)) {
        callbackUsingPOSTWithRequestBuilder(bodyAccessToken: bodyAccessToken).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     {{{token_resource_callback}}}
     
     - POST /api/tokens/callback
     - {{{token_resource_callback_notes}}}
     - examples: [{contentType=application/json, example={
  "AuthToken" : {
    "owner" : "aeiou",
    "code" : "aeiou",
    "id" : 123,
    "extraInfo" : {
      "idEmissor" : 123
    },
    "status" : "aeiou"
  },
  "action" : "aeiou",
  "user" : "aeiou"
}}]
     
     - parameter bodyAccessToken: (body) bodyAccessToken 

     - returns: RequestBuilder<BodyAccessToken> 
     */
    public class func callbackUsingPOSTWithRequestBuilder(bodyAccessToken bodyAccessToken: BodyAccessToken) -> RequestBuilder<BodyAccessToken> {
        let path = "/api/tokens/callback"
        let URLString = PierAPI.basePath + path
        
        let parameters = bodyAccessToken.encodeToJSON() as? [String:AnyObject]

        let requestBuilder: RequestBuilder<BodyAccessToken>.Type = PierAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
    }

}
