//
// GlobaltagpermissaopaisAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class GlobaltagpermissaopaisAPI: APIBase {
    /**
     
     {{{permissao_pais_resource_consultar_pais}}}
     
     - parameter id: (path) {{{permissao_pais_resource_consultar_pais_param_id}}} 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func consultarPaisUsingGET(id id: Int, completion: ((data: PaisResponse?, error: ErrorType?) -> Void)) {
        consultarPaisUsingGETWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     {{{permissao_pais_resource_consultar_pais}}}
     
     - GET /api/paises/{id}
     - {{{permissao_pais_resource_consultar_pais_notes}}}
     - examples: [{contentType=application/json, example={
  "continente" : "aeiou",
  "codigo" : "aeiou",
  "sigla" : "aeiou",
  "id" : 123456789,
  "flagAtivo" : false,
  "descricao" : "aeiou"
}}]
     
     - parameter id: (path) {{{permissao_pais_resource_consultar_pais_param_id}}} 

     - returns: RequestBuilder<PaisResponse> 
     */
    public class func consultarPaisUsingGETWithRequestBuilder(id id: Int) -> RequestBuilder<PaisResponse> {
        var path = "/api/paises/{id}"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = PierAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<PaisResponse>.Type = PierAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     {{{enum_resource_listar_continentes}}}
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func listarContinentesUsingGET(completion: ((data: [AnyObject]?, error: ErrorType?) -> Void)) {
        listarContinentesUsingGETWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     {{{enum_resource_listar_continentes}}}
     
     - GET /api/continentes
     - {{{enum_resource_listar_continentes_notes}}}
     - examples: [{contentType=application/json, example=[ "{}" ]}]

     - returns: RequestBuilder<[AnyObject]> 
     */
    public class func listarContinentesUsingGETWithRequestBuilder() -> RequestBuilder<[AnyObject]> {
        let path = "/api/continentes"
        let URLString = PierAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<[AnyObject]>.Type = PierAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     {{{permissao_pais_resource_listar_paises}}}
     
     - parameter sort: (query) {{{global_menssagem_sort_sort}}} (optional)
     - parameter page: (query) {{{global_menssagem_sort_page_value}}} (optional)
     - parameter limit: (query) {{{global_menssagem_sort_limit}}} (optional)
     - parameter codigo: (query) {{{pais_request_codigo_value}}} (optional)
     - parameter sigla: (query) {{{pais_request_sigla_value}}} (optional)
     - parameter descricao: (query) {{{pais_request_descricao_value}}} (optional)
     - parameter continente: (query) {{{pais_request_continente_value}}} (optional)
     - parameter flagAtivo: (query) {{{pais_request_flag_ativo_value}}} (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func listarPaisesUsingGET(sort sort: [String]?, page: Int?, limit: Int?, codigo: String?, sigla: String?, descricao: String?, continente: String?, flagAtivo: Bool?, completion: ((data: PagePaisResponse?, error: ErrorType?) -> Void)) {
        listarPaisesUsingGETWithRequestBuilder(sort: sort, page: page, limit: limit, codigo: codigo, sigla: sigla, descricao: descricao, continente: continente, flagAtivo: flagAtivo).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     {{{permissao_pais_resource_listar_paises}}}
     
     - GET /api/paises
     - {{{permissao_pais_resource_listar_paises_notes}}}
     - examples: [{contentType=application/json, example={
  "previousPage" : 123,
  "last" : true,
  "hasContent" : true,
  "hasNextPage" : true,
  "nextPage" : 123,
  "content" : [ {
    "continente" : "aeiou",
    "codigo" : "aeiou",
    "sigla" : "aeiou",
    "id" : 123456789,
    "flagAtivo" : false,
    "descricao" : "aeiou"
  } ],
  "totalElements" : 123456789,
  "number" : 123,
  "firstPage" : true,
  "numberOfElements" : 123,
  "size" : 123,
  "totalPages" : 123,
  "hasPreviousPage" : true,
  "first" : true
}}]
     
     - parameter sort: (query) {{{global_menssagem_sort_sort}}} (optional)
     - parameter page: (query) {{{global_menssagem_sort_page_value}}} (optional)
     - parameter limit: (query) {{{global_menssagem_sort_limit}}} (optional)
     - parameter codigo: (query) {{{pais_request_codigo_value}}} (optional)
     - parameter sigla: (query) {{{pais_request_sigla_value}}} (optional)
     - parameter descricao: (query) {{{pais_request_descricao_value}}} (optional)
     - parameter continente: (query) {{{pais_request_continente_value}}} (optional)
     - parameter flagAtivo: (query) {{{pais_request_flag_ativo_value}}} (optional)

     - returns: RequestBuilder<PagePaisResponse> 
     */
    public class func listarPaisesUsingGETWithRequestBuilder(sort sort: [String]?, page: Int?, limit: Int?, codigo: String?, sigla: String?, descricao: String?, continente: String?, flagAtivo: Bool?) -> RequestBuilder<PagePaisResponse> {
        let path = "/api/paises"
        let URLString = PierAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [
            "sort": sort,
            "page": page,
            "limit": limit,
            "codigo": codigo,
            "sigla": sigla,
            "descricao": descricao,
            "continente": continente,
            "flagAtivo": flagAtivo
        ]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<PagePaisResponse>.Type = PierAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
    }

}
