//
// ArquivoParametroResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Objeto Response de par\u00E2metros do arquivo. */
public class ArquivoParametroResponse: JSONEncodable {

    /** C\u00F3digo de identifica\u00E7\u00E3o do detalhe do arquivo. */
    public var id: Int?
    /** Nome que identifica o detalhe do arquivo */
    public var nomeCampo: String?
    /** Conte\u00FAdo do nomeCampo */
    public var conteudo: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["nomeCampo"] = self.nomeCampo
        nillableDictionary["conteudo"] = self.conteudo
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
