//
// BoletoResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Representa\u00E7\u00E3o da resposta do boleto de fatura */
public class BoletoResponse: JSONEncodable {

    /** N\u00FAmero do documento \u00E9 o c\u00F3digo informado pelo banco para identifica\u00E7\u00E3o do cliente */
    public var numeroDoDocumento: String?
    /** Data do processamento (emiss\u00E3o ou faturamento) do boleto */
    public var dataProcessamento: String?
    /** Data do documento (impress\u00E3o) */
    public var dataDocumento: String?
    /** Data do vencimento */
    public var dataVencimento: String?
    /** Data do fechamento */
    public var dataFechamento: String?
    /** Valor do Boleto. */
    public var valorBoleto: Double?
    /** Benefici\u00E1rio \u00E9 a pessoa/empresa que gera o boleto */
    public var nomeBeneficiario: String?
    /** Documento do Beneficiario. */
    public var documentoBeneficiario: String?
    /** Ag\u00EAncia. */
    public var agencia: String?
    /** C\u00F3digo do benefici\u00E1rio */
    public var codigoBeneficiario: String?
    /** N\u00FAmero do conv\u00EAnio fornecido pelo banco \u00E9 o c\u00F3digo que identifica um emissor junto ao seu banco para associar seus boletos. */
    public var numeroConvenio: String?
    /** D\u00EDgito do c\u00F3digo do benefici\u00E1rio */
    public var digitoCodigoBeneficiario: String?
    /** Carteira \u00E9 o c\u00F3digo informado pelo banco pra identifica\u00E7\u00E3o do tipo do boleto */
    public var carteira: String?
    /** Nosso n\u00FAmero \u00E9 o c\u00F3digo que o benefici\u00E1rio escolhe para manter controle sobre seus boletos. Esse valor serve para o cedente identificar quais boletos foram pagos ou n\u00E3o. Recomenda-se o uso de n\u00FAmeros sequ\u00EAnciais, na gera\u00E7\u00E3o de diversos boletos, para facilitar a identifica\u00E7\u00E3o dos boletos pagos */
    public var nossoNumero: String?
    /** D\u00EDgito do nosso n\u00FAmero */
    public var digitoNossoNumero: String?
    /** Banco */
    public var banco: String?
    /** Aceite informa ao banco se deve aceitar o boleto ap\u00F3s a data de vencimento (padr\u00E3o: \&quot;N\&quot;) */
    public var aceite: Bool?
    /** Esp\u00E9cie do documento \u00E9 o identificador do tipo de boleto (padr\u00E3o: \&quot;DV\&quot;) */
    public var especieDoDocumento: String?
    /** Esp\u00E9cie \u00E9 o identificador da moeda do boleto (padr\u00E3o: \&quot;R$\&quot;) */
    public var especie: String?
    /** Instru\u00E7\u00F5es para o benefici\u00E1rio */
    public var instrucoes: [String]?
    /** Locais de pagamento */
    public var locaisDePagamento: [String]?
    /** Pagador \u00E9 a pessoa/empresa que deve pagar o boleto */
    public var nomePagador: String?
    /** Documento do pagador (CPF ou CNPJ) */
    public var documentoPagador: String?
    /** Logradouro do pagador */
    public var logradouroPagador: String?
    /** Bairro do pagador */
    public var bairroPagador: String?
    /** CEP do pagador */
    public var cepPagador: String?
    /** Cidade do pagador */
    public var cidadePagador: String?
    /** Unidade federativa do pagador */
    public var ufPagador: String?
    /** Valor num\u00E9rico do c\u00F3digo de barras */
    public var codigoDeBarras: String?
    /** Linha digit\u00E1vel formatada */
    public var linhaDigitavel: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["numeroDoDocumento"] = self.numeroDoDocumento
        nillableDictionary["dataProcessamento"] = self.dataProcessamento
        nillableDictionary["dataDocumento"] = self.dataDocumento
        nillableDictionary["dataVencimento"] = self.dataVencimento
        nillableDictionary["dataFechamento"] = self.dataFechamento
        nillableDictionary["valorBoleto"] = self.valorBoleto
        nillableDictionary["nomeBeneficiario"] = self.nomeBeneficiario
        nillableDictionary["documentoBeneficiario"] = self.documentoBeneficiario
        nillableDictionary["agencia"] = self.agencia
        nillableDictionary["codigoBeneficiario"] = self.codigoBeneficiario
        nillableDictionary["numeroConvenio"] = self.numeroConvenio
        nillableDictionary["digitoCodigoBeneficiario"] = self.digitoCodigoBeneficiario
        nillableDictionary["carteira"] = self.carteira
        nillableDictionary["nossoNumero"] = self.nossoNumero
        nillableDictionary["digitoNossoNumero"] = self.digitoNossoNumero
        nillableDictionary["banco"] = self.banco
        nillableDictionary["aceite"] = self.aceite
        nillableDictionary["especieDoDocumento"] = self.especieDoDocumento
        nillableDictionary["especie"] = self.especie
        nillableDictionary["instrucoes"] = self.instrucoes?.encodeToJSON()
        nillableDictionary["locaisDePagamento"] = self.locaisDePagamento?.encodeToJSON()
        nillableDictionary["nomePagador"] = self.nomePagador
        nillableDictionary["documentoPagador"] = self.documentoPagador
        nillableDictionary["logradouroPagador"] = self.logradouroPagador
        nillableDictionary["bairroPagador"] = self.bairroPagador
        nillableDictionary["cepPagador"] = self.cepPagador
        nillableDictionary["cidadePagador"] = self.cidadePagador
        nillableDictionary["ufPagador"] = self.ufPagador
        nillableDictionary["codigoDeBarras"] = self.codigoDeBarras
        nillableDictionary["linhaDigitavel"] = self.linhaDigitavel
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
