//
// CancelamentoTransacaoOnUsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** {{{cancelamento_transacao_on_us_request_description}}} */
public class CancelamentoTransacaoOnUsRequest: JSONEncodable {

    /** {{{cancelamento_transacao_on_us_request_nsu_autorizacao_transacao_cancelada_value}}} */
    public var nsuAutorizacaoTransacaoCancelada: String?
    /** {{{transacao_on_us_request_nsu_origem_value}}} */
    public var nsuOrigem: String?
    /** {{{desfazimento_transacao_on_us_request_nsu_origem_transacao_cancelada_value}}} */
    public var nsuOrigemTransacaoCancelada: String?
    /** {{{transacao_on_us_request_codigo_processamento_value}}} */
    public var codigoProcessamento: String?
    /** {{{desfazimento_transacao_on_us_request_data_hora_transacao_cancelada_value}}} */
    public var dataHoraTransacaoCancelada: String?
    /** {{{transacao_on_us_request_valor_transacao_value}}} */
    public var valorTransacao: Double?
    /** {{{transacao_on_us_request_numero_real_cartao_value}}} */
    public var numeroRealCartao: String?
    /** {{{transacao_on_us_request_data_validade_cartao_value}}} */
    public var dataValidadeCartao: String?
    /** {{{transacao_on_us_request_numero_estabelecimento_value}}} */
    public var numeroEstabelecimento: Int?
    /** {{{transacao_on_us_request_data_hora_terminal_value}}} */
    public var dataHoraTerminal: String?
    /** {{{transacao_on_us_request_terminal_requisitante_value}}} */
    public var terminalRequisitante: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["nsuAutorizacaoTransacaoCancelada"] = self.nsuAutorizacaoTransacaoCancelada
        nillableDictionary["nsuOrigem"] = self.nsuOrigem
        nillableDictionary["nsuOrigemTransacaoCancelada"] = self.nsuOrigemTransacaoCancelada
        nillableDictionary["codigoProcessamento"] = self.codigoProcessamento
        nillableDictionary["dataHoraTransacaoCancelada"] = self.dataHoraTransacaoCancelada
        nillableDictionary["valorTransacao"] = self.valorTransacao
        nillableDictionary["numeroRealCartao"] = self.numeroRealCartao
        nillableDictionary["dataValidadeCartao"] = self.dataValidadeCartao
        nillableDictionary["numeroEstabelecimento"] = self.numeroEstabelecimento
        nillableDictionary["dataHoraTerminal"] = self.dataHoraTerminal
        nillableDictionary["terminalRequisitante"] = self.terminalRequisitante
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
