//
// CodigoSegurancaSMSPersist.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Representa\u00E7\u00E3o da requisi\u00E7\u00E3o do recurso gerar c\u00F3digo de seguran\u00E7a. */
public class CodigoSegurancaSMSPersist: JSONEncodable {

    /** DDD do n\u00FAmero de telefone para envio do sms. */
    public var ddd: String?
    /** N\u00FAmero do telefone para envio do sms. */
    public var telefone: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["ddd"] = self.ddd
        nillableDictionary["telefone"] = self.telefone
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
