//
// CompraContestadaTransacaoResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** {{{codigo_chargeback_response_description}}} */
public class CompraContestadaTransacaoResponse: JSONEncodable {

    public var agingCompras: Int?
    public var agingContestacao: Int?
    public var bandeira: String?
    public var codigoAutorizacao: String?
    public var codigoContestacao: String?
    public var codigoEventoCompra: String?
    public var codigoMoedaDestino: String?
    public var data2Reapresentacao: String?
    public var dataAlteracao: NSDate?
    public var dataContestacao: NSDate?
    public var dataEnvioCB: String?
    public var dataTransacao: NSDate?
    public var historico: String?
    public var idCompraContestada: Int?
    public var internacional: Int?
    public var mcc: String?
    public var modoDeEntradaDescricao: String?
    public var modoEntrada: String?
    public var motivo2Reapresentacao: String?
    public var nomeEstabelecimento: String?
    public var numeroControle: String?
    public var razaoCB: String?
    public var referenceNumber: String?
    public var reporteBandeira: String?
    public var responsavelAbertuda: String?
    public var responsavelAlteracao: String?
    public var statusContestacao: String?
    public var texto2Reapresentacao: String?
    public var tipoTransacao: String?
    public var transacaoSegura: String?
    public var valorCompra: Double?
    public var valorContrato: Double?
    public var valorDestino: Double?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["agingCompras"] = self.agingCompras
        nillableDictionary["agingContestacao"] = self.agingContestacao
        nillableDictionary["bandeira"] = self.bandeira
        nillableDictionary["codigoAutorizacao"] = self.codigoAutorizacao
        nillableDictionary["codigoContestacao"] = self.codigoContestacao
        nillableDictionary["codigoEventoCompra"] = self.codigoEventoCompra
        nillableDictionary["codigoMoedaDestino"] = self.codigoMoedaDestino
        nillableDictionary["data2Reapresentacao"] = self.data2Reapresentacao
        nillableDictionary["dataAlteracao"] = self.dataAlteracao?.encodeToJSON()
        nillableDictionary["dataContestacao"] = self.dataContestacao?.encodeToJSON()
        nillableDictionary["dataEnvioCB"] = self.dataEnvioCB
        nillableDictionary["dataTransacao"] = self.dataTransacao?.encodeToJSON()
        nillableDictionary["historico"] = self.historico
        nillableDictionary["idCompraContestada"] = self.idCompraContestada
        nillableDictionary["internacional"] = self.internacional
        nillableDictionary["mcc"] = self.mcc
        nillableDictionary["modoDeEntradaDescricao"] = self.modoDeEntradaDescricao
        nillableDictionary["modoEntrada"] = self.modoEntrada
        nillableDictionary["motivo2Reapresentacao"] = self.motivo2Reapresentacao
        nillableDictionary["nomeEstabelecimento"] = self.nomeEstabelecimento
        nillableDictionary["numeroControle"] = self.numeroControle
        nillableDictionary["razaoCB"] = self.razaoCB
        nillableDictionary["referenceNumber"] = self.referenceNumber
        nillableDictionary["reporteBandeira"] = self.reporteBandeira
        nillableDictionary["responsavelAbertuda"] = self.responsavelAbertuda
        nillableDictionary["responsavelAlteracao"] = self.responsavelAlteracao
        nillableDictionary["statusContestacao"] = self.statusContestacao
        nillableDictionary["texto2Reapresentacao"] = self.texto2Reapresentacao
        nillableDictionary["tipoTransacao"] = self.tipoTransacao
        nillableDictionary["transacaoSegura"] = self.transacaoSegura
        nillableDictionary["valorCompra"] = self.valorCompra
        nillableDictionary["valorContrato"] = self.valorContrato
        nillableDictionary["valorDestino"] = self.valorDestino
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
