//
// DetalheOportunidadePersist.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Objeto DetalheOportunidade */
public class DetalheOportunidadePersist: JSONEncodable {

    /** Conte\u00C3\u00BAdo do detalhe */
    public var conteudo: String?
    /** Nome do conte\u00C3\u00BAdo */
    public var nomeCampo: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["conteudo"] = self.conteudo
        nillableDictionary["nomeCampo"] = self.nomeCampo
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
