//
// DetalheOperacaoResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Representa\u00E7\u00E3o da resposta do recurso Operacao */
public class DetalheOperacaoResponse: JSONEncodable {

    /** C\u00F3digo que identifica a opera\u00E7\u00E3o */
    public var idOperacao: Int?
    /** C\u00F3digo de processamento usado em transa\u00E7\u00F5es com o autorizador */
    public var codigoProcessamento: String?
    /** C\u00F3digo de processamento usado para cancelar transa\u00E7\u00F5es no autorizador */
    public var codigoProcessamentoCancelamento: String?
    /** Nome da opera\u00E7\u00E3o */
    public var nomeOperacao: String?
    /** Descri\u00E7\u00E3o da opera\u00E7\u00E3o */
    public var descricaoOperacao: String?
    /** Quantidade m\u00EDnima de meses permitido para opera\u00E7\u00E3o */
    public var planoMinimo: Int?
    /** Quantidade M\u00E1ximo de meses permitido para opera\u00E7\u00E3o */
    public var planoMaximo: Int?
    /**  Valor m\u00EDnimo permitido permitido para opera\u00E7\u00E3o */
    public var valorMinimo: Double?
    /**  Valor m\u00E1ximo permitido permitido para opera\u00E7\u00E3o */
    public var valorMaximo: Double?
    /** Flag indicativa para crobran\u00E7a de juros */
    public var flagCobraJuros: Bool?
    /** Valor do juros a ser cobrado, caso opera\u00E7\u00E3o cobre juros */
    public var taxaJuros: Double?
    /** Flag indicativa para crobran\u00E7a de tarifas */
    public var flagCobraTarifa: Bool?
    /** Valor da tarifa a ser cobrado, caso opera\u00E7\u00E3o cobre tarifas */
    public var taxaTarifa: Double?
    /** Valor da taxa de abertura de conta */
    public var valorTac: Double?
    /** Percentual da taxa de abertura de conta */
    public var percentualTac: Double?
    /** Valor da opera\u00E7\u00E3o */
    public var valorOperacao: Double?
    /** Quantidade de meses para car\u00EAncia */
    public var carencia: Int?
    /** Valor excedente permitido para opera\u00E7\u00E3o */
    public var excedentePermitido: Double?
    /** Permitir transa\u00E7\u00F5es parceladas */
    public var flagPermitirParcelamento: Bool?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["idOperacao"] = self.idOperacao
        nillableDictionary["codigoProcessamento"] = self.codigoProcessamento
        nillableDictionary["codigoProcessamentoCancelamento"] = self.codigoProcessamentoCancelamento
        nillableDictionary["nomeOperacao"] = self.nomeOperacao
        nillableDictionary["descricaoOperacao"] = self.descricaoOperacao
        nillableDictionary["planoMinimo"] = self.planoMinimo
        nillableDictionary["planoMaximo"] = self.planoMaximo
        nillableDictionary["valorMinimo"] = self.valorMinimo
        nillableDictionary["valorMaximo"] = self.valorMaximo
        nillableDictionary["flagCobraJuros"] = self.flagCobraJuros
        nillableDictionary["taxaJuros"] = self.taxaJuros
        nillableDictionary["flagCobraTarifa"] = self.flagCobraTarifa
        nillableDictionary["taxaTarifa"] = self.taxaTarifa
        nillableDictionary["valorTac"] = self.valorTac
        nillableDictionary["percentualTac"] = self.percentualTac
        nillableDictionary["valorOperacao"] = self.valorOperacao
        nillableDictionary["carencia"] = self.carencia
        nillableDictionary["excedentePermitido"] = self.excedentePermitido
        nillableDictionary["flagPermitirParcelamento"] = self.flagPermitirParcelamento
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
