//
// DetalhesFaturaResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Objeto contendo os detalhes de uma fatura */
public class DetalhesFaturaResponse: JSONEncodable {

    /** Apresenta os detalhes da fatura */
    public var fatura: FaturaFechadaResponse?
    /** Apresenta as transa\u00E7\u00F5es relacionadas a fatura. */
    public var transacoes: [TransacoesCorrentesResponse]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["fatura"] = self.fatura?.encodeToJSON()
        nillableDictionary["transacoes"] = self.transacoes?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
