//
// DocumentoResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** {{{documento_response_description}}} */
public class DocumentoResponse: JSONEncodable {

    /** {{{documento_response_id_value}}} */
    public var id: Int?
    /** {{{documento_response_id_template_documento_value}}} */
    public var idTemplateDocumento: Int?
    /** {{{documento_response_nome_value}}} */
    public var nome: String?
    /** {{{documento_response_extensao_value}}} */
    public var extensao: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["idTemplateDocumento"] = self.idTemplateDocumento
        nillableDictionary["nome"] = self.nome
        nillableDictionary["extensao"] = self.extensao
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
