//
// EnderecoAprovadoResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** {{{endereco_aprovado_response_description}}} */
public class EnderecoAprovadoResponse: JSONEncodable {

    /** {{{endereco_aprovado_response_id_value}}} */
    public var id: Int?
    /** {{{endereco_aprovado_response_id_tipo_endereco_value}}} */
    public var idTipoEndereco: Int?
    /** {{{endereco_aprovado_response_cep_value}}} */
    public var cep: String?
    /** {{{endereco_aprovado_response_logradouro_value}}} */
    public var logradouro: String?
    /** {{{endereco_aprovado_response_numero_value}}} */
    public var numero: Int?
    /** {{{endereco_aprovado_response_complemento_value}}} */
    public var complemento: String?
    /** {{{endereco_aprovado_response_ponto_referencia_value}}} */
    public var pontoReferencia: String?
    /** {{{endereco_aprovado_response_bairro_value}}} */
    public var bairro: String?
    /** {{{endereco_aprovado_response_cidade_value}}} */
    public var cidade: String?
    /** {{{endereco_aprovado_response_uf_value}}} */
    public var uf: String?
    /** {{{endereco_aprovado_response_pais_value}}} */
    public var pais: String?
    /** {{{endereco_aprovado_response_endereco_correspondencia_value}}} */
    public var enderecoCorrespondencia: Bool?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["idTipoEndereco"] = self.idTipoEndereco
        nillableDictionary["cep"] = self.cep
        nillableDictionary["logradouro"] = self.logradouro
        nillableDictionary["numero"] = self.numero
        nillableDictionary["complemento"] = self.complemento
        nillableDictionary["pontoReferencia"] = self.pontoReferencia
        nillableDictionary["bairro"] = self.bairro
        nillableDictionary["cidade"] = self.cidade
        nillableDictionary["uf"] = self.uf
        nillableDictionary["pais"] = self.pais
        nillableDictionary["enderecoCorrespondencia"] = self.enderecoCorrespondencia
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
