//
// EntidadeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** {{{entidade_response_description}}} */
public class EntidadeResponse: JSONEncodable {

    /** {{{entidade_response_id_value}}} */
    public var id: Int?
    /** {{{entidade_response_descricao_value}}} */
    public var descricao: String?
    /** {{{entidade_response_flag_ativo_value}}} */
    public var flagAtivo: Bool?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["descricao"] = self.descricao
        nillableDictionary["flagAtivo"] = self.flagAtivo
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
