//
// EstabelecimentoPersist.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Par\u00C3\u00A2metros de requisi\u00C3\u00A7\u00C3\u00A3o de um estabelecimento */
public class EstabelecimentoPersist: JSONEncodable {

    public enum TipoPagamento: String { 
        case Centralizado = "CENTRALIZADO"
        case Pv = "PV"
    }
    
    /** Indica se \u00C3\u00A9 matriz ou filial. */
    public var flagMatriz: Int?
    /** Apresenta o n\u00C3\u00BAmero de identifica\u00C3\u00A7\u00C3\u00A3o do Credor. */
    public var idCredor: Int?
    /** Apresenta o n\u00C3\u00BAmero de identifica\u00C3\u00A7\u00C3\u00A3o do Estabelecimento na Receita Federal. */
    public var numeroReceitaFederal: String?
    /** Nome do Estabelecimento. */
    public var nome: String?
    /** Raz\u00C3\u00A3o Social do Estabelecimento. */
    public var descricao: String?
    /** T\u00C3\u00ADtulo Comercial do Estabelecimento. */
    public var nomeFantasia: String?
    /** C\u00C3\u00B3digo de Endere\u00C3\u00A7amento Postal (CEP). */
    public var cep: String?
    /** Nome do Logradouro. */
    public var nomeLogradouro: String?
    /** N\u00C3\u00BAmero do endere\u00C3\u00A7o. */
    public var numeroEndereco: Int?
    /** Nome do bairro do endere\u00C3\u00A7o. */
    public var bairro: String?
    /** Nome da cidade do endere\u00C3\u00A7o. */
    public var cidade: String?
    /** Descri\u00C3\u00A7\u00C3\u00B5es complementares referente ao endere\u00C3\u00A7o. */
    public var complemento: String?
    /** Sigla de identifica\u00C3\u00A7\u00C3\u00A3o da Unidade Federativa do endere\u00C3\u00A7o. */
    public var uf: String?
    /** C\u00C3\u00B3digo de Endere\u00C3\u00A7amento Postal (CEP). */
    public var cep2: String?
    /** Nome do Logradouro . */
    public var nomeLogradouro2: String?
    /** N\u00C3\u00BAmero do endere\u00C3\u00A7o. */
    public var numeroEndereco2: Int?
    /** Nome do bairro do endere\u00C3\u00A7o. */
    public var bairro2: String?
    /** Nome da cidade do endere\u00C3\u00A7o. */
    public var cidade2: String?
    /** Descri\u00C3\u00A7\u00C3\u00B5es complementares referente ao endere\u00C3\u00A7o. */
    public var complemento2: String?
    /** Sigla de identifica\u00C3\u00A7\u00C3\u00A3o da Unidade Federativa do endere\u00C3\u00A7o. */
    public var uf2: String?
    /** Detalhes espec\u00C3\u00ADficos quanto ao Cadastro do Estabelecimento. */
    public var obs: String?
    /** Nome da pessoa para contato com o Estabelecimento. */
    public var contato: String?
    /** E-mail da pessoa para contato com o Estabelecimento. */
    public var email: String?
    /** Indica se o estabelecimento ser\u00C3\u00A1 inclu\u00C3\u00ADdo no arquivo de registro para a Secretaria da Fazenda Estadual. */
    public var flagArquivoSecrFazenda: Int?
    /** Indica se o estabelecimento poder\u00C3\u00A1 originar transa\u00C3\u00A7\u00C3\u00B5es sem a leitura da tarja ou do chip do cart\u00C3\u00A3o. */
    public var flagCartaoDigitado: Int?
    /** Indica se o estabelecimento est\u00C3\u00A1 inativo. */
    public var inativo: Int?
    /** C\u00C3\u00B3digo identificador da moeda. */
    public var idMoeda: Int?
    /** Identificador de Pa\u00C3\u00ADs. */
    public var idPais: Int?
    /** N\u00C3\u00BAmero do associado ao SPCBrasil. */
    public var associadoSPCBrasil: Int?
    /** C\u00C3\u00B3digo de Categoria de Mercado. */
    public var mcc: Int?
    /** C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o do Estabelecimento. */
    public var idTipoEstabelecimento: Int?
    /** Indicador para qual endere\u00C3\u00A7o as correspond\u00C3\u00AAncias ser\u00C3\u00A3o enviadas, onde 1 \u00C3\u00A9 ORIGEM e 2 ENDERE\u00C3\u0087O DE CORRESPOND\u00C3\u008ANCIA. */
    public var correspondencia: Int?
    /** Cargo do contato do estabelecimento. */
    public var cargoContato: String?
    /** Tipo do regime de pagamento do estabelecimento. */
    public var tipoPagamento: TipoPagamento?
    /** Consulta de cadastro n\u00C3\u00BAmero um. */
    public var consulta: ConsultaCadastroEstabelecimentoDTO?
    /** Consulta de cadastro n\u00C3\u00BAmero um. */
    public var consulta2: ConsultaCadastroEstabelecimentoDTO?
    /** Consulta de cadastro n\u00C3\u00BAmero um. */
    public var consulta3: ConsultaCadastroEstabelecimentoDTO?
    /** Flag indicando se o terminal \u00C3\u00A9 f\u00C3\u00ADsico ou virtual, sendo: (true: Sim), (false: N\u00C3\u00A3o)). */
    public var flagTerminalVirtual: Bool?
    /** Flag indicando se o terminal permite consultar extrato, sendo: (true: Sim), (false: N\u00C3\u00A3o)). */
    public var flagConsultaExtrato: Bool?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["flagMatriz"] = self.flagMatriz
        nillableDictionary["idCredor"] = self.idCredor
        nillableDictionary["numeroReceitaFederal"] = self.numeroReceitaFederal
        nillableDictionary["nome"] = self.nome
        nillableDictionary["descricao"] = self.descricao
        nillableDictionary["nomeFantasia"] = self.nomeFantasia
        nillableDictionary["cep"] = self.cep
        nillableDictionary["nomeLogradouro"] = self.nomeLogradouro
        nillableDictionary["numeroEndereco"] = self.numeroEndereco
        nillableDictionary["bairro"] = self.bairro
        nillableDictionary["cidade"] = self.cidade
        nillableDictionary["complemento"] = self.complemento
        nillableDictionary["uf"] = self.uf
        nillableDictionary["cep2"] = self.cep2
        nillableDictionary["nomeLogradouro2"] = self.nomeLogradouro2
        nillableDictionary["numeroEndereco2"] = self.numeroEndereco2
        nillableDictionary["bairro2"] = self.bairro2
        nillableDictionary["cidade2"] = self.cidade2
        nillableDictionary["complemento2"] = self.complemento2
        nillableDictionary["uf2"] = self.uf2
        nillableDictionary["obs"] = self.obs
        nillableDictionary["contato"] = self.contato
        nillableDictionary["email"] = self.email
        nillableDictionary["flagArquivoSecrFazenda"] = self.flagArquivoSecrFazenda
        nillableDictionary["flagCartaoDigitado"] = self.flagCartaoDigitado
        nillableDictionary["inativo"] = self.inativo
        nillableDictionary["idMoeda"] = self.idMoeda
        nillableDictionary["idPais"] = self.idPais
        nillableDictionary["associadoSPCBrasil"] = self.associadoSPCBrasil
        nillableDictionary["mcc"] = self.mcc
        nillableDictionary["idTipoEstabelecimento"] = self.idTipoEstabelecimento
        nillableDictionary["correspondencia"] = self.correspondencia
        nillableDictionary["cargoContato"] = self.cargoContato
        nillableDictionary["tipoPagamento"] = self.tipoPagamento?.rawValue
        nillableDictionary["consulta"] = self.consulta?.encodeToJSON()
        nillableDictionary["consulta2"] = self.consulta2?.encodeToJSON()
        nillableDictionary["consulta3"] = self.consulta3?.encodeToJSON()
        nillableDictionary["flagTerminalVirtual"] = self.flagTerminalVirtual
        nillableDictionary["flagConsultaExtrato"] = self.flagConsultaExtrato
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
