//
// HistoricoAtrasoFaturaResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Hist\u00C3\u00B3rico Pagamento Fatura Atraso */
public class HistoricoAtrasoFaturaResponse: JSONEncodable {

    /** Data vencimento fatura. */
    public var dataVencimento: String?
    /** Quantidade de dias em atraso. */
    public var diasPagamentoAposVencimento: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["dataVencimento"] = self.dataVencimento
        nillableDictionary["diasPagamentoAposVencimento"] = self.diasPagamentoAposVencimento
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
