//
// HistoricoTelefoneResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Objeto de resposta para historico de telefones */
public class HistoricoTelefoneResponse: JSONEncodable {

    /** C\u00F3digo de Identifica\u00E7\u00E3o do Telefone (id). */
    public var id: Int?
    /** Apresenta o N\u00FAmero do telefone. */
    public var telefone: String?
    /** Apresenta o id do tipo do telefone. */
    public var idTipoTelefone: Int?
    /** Apresenta a descri\u00E7\u00E3o do tipo do telefone. */
    public var tipoTelefone: String?
    /** Apresenta a data que o telefone fora alterado. */
    public var dataModificacao: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["telefone"] = self.telefone
        nillableDictionary["idTipoTelefone"] = self.idTipoTelefone
        nillableDictionary["tipoTelefone"] = self.tipoTelefone
        nillableDictionary["dataModificacao"] = self.dataModificacao
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
