//
// InscricaoApnPersistencia.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** {{{inscricao_apn_persistencia_descricao}}} */
public class InscricaoApnPersistencia: JSONEncodable {

    /** {{{inscricao_apn_persistencia_device_token_descricao}}} */
    public var deviceToken: String?
    /** {{{inscricao_apn_persistencia_id_aplicacao_mobile_descricao}}} */
    public var idAplicacaoMobile: Int?
    /** {{{inscricao_apn_persistencia_id_cartoes_descricao}}} */
    public var idCartoes: [Int]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["deviceToken"] = self.deviceToken
        nillableDictionary["idAplicacaoMobile"] = self.idAplicacaoMobile
        nillableDictionary["idCartoes"] = self.idCartoes?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
