//
// IntegracaoEmissorPersist.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** {{{integracao_emissor_persist_description}}} */
public class IntegracaoEmissorPersist: JSONEncodable {

    /** {{{integracao_emissor_persist_canal_entrada_value}}} */
    public var canalEntrada: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["canalEntrada"] = self.canalEntrada
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
