//
// LimiteDisponibilidadeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Limite Disponibilidade */
public class LimiteDisponibilidadeResponse: JSONEncodable {

    /** C\u00C3\u00B3digo de Identifica\u00C3\u00A7\u00C3\u00A3o de Limite e Disponibilidade (id). */
    public var id: Int?
    /** Valor do limite de cr\u00C3\u00A9dito. */
    public var limiteGlobal: Double?
    /** Valor do limite de cr\u00C3\u00A9dito para uso exclusivo em compras nacionais. */
    public var limiteCompra: Double?
    /** Valor do limite de cr\u00C3\u00A9dito para transa\u00C3\u00A7\u00C3\u00B5es de compras parceladas. */
    public var limiteParcelado: Double?
    /** Valor do limite de cr\u00C3\u00A9dito acumulado da soma das parcelas das compras que forem realizadas nesta modalidade. */
    public var limiteParcelas: Double?
    /** Valor do limite de cr\u00C3\u00A9dito para transa\u00C3\u00A7\u00C3\u00B5es de Saque Nacional. */
    public var limiteSaqueGlobal: Double?
    /** Valor do limite de cr\u00C3\u00A9dito para transa\u00C3\u00A7\u00C3\u00B5es de Saque Nacional dentro de cada ciclo de faturamento. */
    public var limiteSaquePeriodo: Double?
    /** Valor da margem de cr\u00C3\u00A9dito para consigna\u00C3\u00A7\u00C3\u00B5es (desconto em folha). */
    public var limiteConsignado: Double?
    /** Valor do limite de cr\u00C3\u00A9dito para uso exclusivo em compras internacionais. */
    public var limiteInternacionalCompra: Double?
    /** Valor do limite de cr\u00C3\u00A9dito para transa\u00C3\u00A7\u00C3\u00B5es internacionais de compras parceladas. */
    public var limiteInternacionalParcelado: Double?
    /** Valor do limite de cr\u00C3\u00A9dito acumulado da soma das parcelas das compras internacionais que forem realizadas nesta modalidade. */
    public var limiteInternacionalParcelas: Double?
    /** Valor do limite de cr\u00C3\u00A9dito para transa\u00C3\u00A7\u00C3\u00B5es de saque internacional. */
    public var limiteInternacionalSaqueGlobal: Double?
    /** Valor do limite de cr\u00C3\u00A9dito para transa\u00C3\u00A7\u00C3\u00B5es de saque internacional dentro de cada ciclo de faturamento. */
    public var limiteInternacionalSaquePeriodo: Double?
    /** Valor m\u00C3\u00A1ximo do limite de cr\u00C3\u00A9dito para realizar transa\u00C3\u00A7\u00C3\u00B5es. */
    public var limiteMaximo: Double?
    /** Valor de cr\u00C3\u00A9dito dispon\u00C3\u00ADvel para transa\u00C3\u00A7\u00C3\u00B5es. */
    public var saldoDisponivelGlobal: Double?
    /** Valor de cr\u00C3\u00A9dito dispon\u00C3\u00ADvel para transa\u00C3\u00A7\u00C3\u00B5es de compra nacional. */
    public var saldoDisponivelCompra: Double?
    /** Valor de cr\u00C3\u00A9dito dispon\u00C3\u00ADvel para transa\u00C3\u00A7\u00C3\u00B5es de compra nacional parcelada. */
    public var saldoDisponivelParcelado: Double?
    /** Valor de cr\u00C3\u00A9dito dispon\u00C3\u00ADvel para utilizar como valor de parcelas Nacionais em um determinado ciclo de faturamento. */
    public var saldoDisponivelParcelas: Double?
    /** Valor de cr\u00C3\u00A9dito que o portador possui dispon\u00C3\u00ADvel para realizar transa\u00C3\u00A7\u00C3\u00B5es de Saque Nacional. */
    public var saldoDisponivelSaque: Double?
    /** Saldo atual de pontos do programa de fidelidade. */
    public var saldoPontosFidelidade: Double?
    /** Valor de cr\u00C3\u00A9dito dispon\u00C3\u00ADvel para transa\u00C3\u00A7\u00C3\u00B5es de compra internacional. */
    public var saldoDisponivelCompraInternacional: Double?
    /** Valor de cr\u00C3\u00A9dito dispon\u00C3\u00ADvel para transa\u00C3\u00A7\u00C3\u00B5es de saque internacional. */
    public var saldoDisponivelSaqueInternacional: Double?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["limiteGlobal"] = self.limiteGlobal
        nillableDictionary["limiteCompra"] = self.limiteCompra
        nillableDictionary["limiteParcelado"] = self.limiteParcelado
        nillableDictionary["limiteParcelas"] = self.limiteParcelas
        nillableDictionary["limiteSaqueGlobal"] = self.limiteSaqueGlobal
        nillableDictionary["limiteSaquePeriodo"] = self.limiteSaquePeriodo
        nillableDictionary["limiteConsignado"] = self.limiteConsignado
        nillableDictionary["limiteInternacionalCompra"] = self.limiteInternacionalCompra
        nillableDictionary["limiteInternacionalParcelado"] = self.limiteInternacionalParcelado
        nillableDictionary["limiteInternacionalParcelas"] = self.limiteInternacionalParcelas
        nillableDictionary["limiteInternacionalSaqueGlobal"] = self.limiteInternacionalSaqueGlobal
        nillableDictionary["limiteInternacionalSaquePeriodo"] = self.limiteInternacionalSaquePeriodo
        nillableDictionary["limiteMaximo"] = self.limiteMaximo
        nillableDictionary["saldoDisponivelGlobal"] = self.saldoDisponivelGlobal
        nillableDictionary["saldoDisponivelCompra"] = self.saldoDisponivelCompra
        nillableDictionary["saldoDisponivelParcelado"] = self.saldoDisponivelParcelado
        nillableDictionary["saldoDisponivelParcelas"] = self.saldoDisponivelParcelas
        nillableDictionary["saldoDisponivelSaque"] = self.saldoDisponivelSaque
        nillableDictionary["saldoPontosFidelidade"] = self.saldoPontosFidelidade
        nillableDictionary["saldoDisponivelCompraInternacional"] = self.saldoDisponivelCompraInternacional
        nillableDictionary["saldoDisponivelSaqueInternacional"] = self.saldoDisponivelSaqueInternacional
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
