//
// LoteCartoesPrePagosResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** {{{lote_cartoes_pre_pagos_response_description}}} */
public class LoteCartoesPrePagosResponse: JSONEncodable {

    /** {{{lote_cartoes_pre_pagos_response_id_value}}} */
    public var id: Int?
    /** {{{lote_cartoes_pre_pagos_response_id_origem_comercial_value}}} */
    public var idOrigemComercial: Int?
    /** {{{lote_cartoes_pre_pagos_response_id_produto_value}}} */
    public var idProduto: Int?
    /** {{{lote_cartoes_pre_pagos_response_id_tipo_cartao_value}}} */
    public var idTipoCartao: Int?
    /** {{{lote_cartoes_pre_pagos_response_id_imagem_value}}} */
    public var idImagem: Int?
    /** {{{lote_cartoes_pre_pagos_response_id_endereco_value}}} */
    public var idEndereco: Int?
    /** {{{lote_cartoes_pre_pagos_response_quantidade_value}}} */
    public var quantidade: Int?
    /** {{{lote_cartoes_pre_pagos_response_data_cadastro_value}}} */
    public var dataCadastro: String?
    /** {{{lote_cartoes_pre_pagos_response_usuario_cadastro_value}}} */
    public var usuarioCadastro: String?
    /** {{{lote_cartoes_pre_pagos_response_status_processamento_value}}} */
    public var statusProcessamento: Int?
    /** {{{lote_cartoes_pre_pagos_response_identificador_externo_value}}} */
    public var identificadorExterno: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["idOrigemComercial"] = self.idOrigemComercial
        nillableDictionary["idProduto"] = self.idProduto
        nillableDictionary["idTipoCartao"] = self.idTipoCartao
        nillableDictionary["idImagem"] = self.idImagem
        nillableDictionary["idEndereco"] = self.idEndereco
        nillableDictionary["quantidade"] = self.quantidade
        nillableDictionary["dataCadastro"] = self.dataCadastro
        nillableDictionary["usuarioCadastro"] = self.usuarioCadastro
        nillableDictionary["statusProcessamento"] = self.statusProcessamento
        nillableDictionary["identificadorExterno"] = self.identificadorExterno
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
