//
// MoedaResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Tipo de moeda */
public class MoedaResponse: JSONEncodable {

    /** Identificador do tipo de moeda. */
    public var id: Int?
    /** C\u00F3digo identificador do tipo de moeda. */
    public var codigoMoeda: String?
    /** S\u00EDmbolo da Moeda. */
    public var simbolo: String?
    /** Descri\u00E7\u00E3o do tipo da moeda. */
    public var descricao: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["codigoMoeda"] = self.codigoMoeda
        nillableDictionary["simbolo"] = self.simbolo
        nillableDictionary["descricao"] = self.descricao
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
