//
// NotificacaoResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Objeto Notifica\u00E7\u00E3o SMS */
public class NotificacaoResponse: JSONEncodable {

    /** N\u00FAmero do protocolo de envio de notifica\u00E7\u00F5es */
    public var protocolo: String?
    /** Mensagem de resposta da solicita\u00E7\u00F5es de envio */
    public var mensagem: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["protocolo"] = self.protocolo
        nillableDictionary["mensagem"] = self.mensagem
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
