//
// NotificacaoSMSBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Objeto Notifica\u00C3\u00A7\u00C3\u00A3o */
public class NotificacaoSMSBody: JSONEncodable {

    public enum TipoEvento: String { 
        case RiscoFraude = "RISCO_FRAUDE"
        case Outros = "OUTROS"
    }
    
    /** N\u00C3\u00BAmero sequencial \u00C3\u00BAnico */
    public var nsu: Int?
    /** C\u00C3\u00B3digo identificado da pessoa */
    public var idPessoa: Int?
    /** C\u00C3\u00B3digo identificador da conta */
    public var idConta: Int?
    /** Apresenta o celular a ser eviado o SMS no formato 5588999999999 ou 5588999999999. */
    public var celular: String?
    /** Apresenta o texto do SMS a ser enviado */
    public var conteudo: String?
    /** Apresenta a data e hora em que ser\u00C3\u00A1 enviado a notifica\u00C3\u00A7\u00C3\u00A3o */
    public var dataAgendamento: NSDate?
    /** Apresenta o tipoEvento a qual pertence a notifica\u00C3\u00A7\u00C3\u00A3o */
    public var tipoEvento: TipoEvento?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["nsu"] = self.nsu
        nillableDictionary["idPessoa"] = self.idPessoa
        nillableDictionary["idConta"] = self.idConta
        nillableDictionary["celular"] = self.celular
        nillableDictionary["conteudo"] = self.conteudo
        nillableDictionary["dataAgendamento"] = self.dataAgendamento?.encodeToJSON()
        nillableDictionary["tipoEvento"] = self.tipoEvento?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
