//
// PessoaJuridicaAprovadaPersist.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** PessoaJuridicaAprovadaPersist */
public class PessoaJuridicaAprovadaPersist: JSONEncodable {

    /** Apresenta o nome completo da raz\u00E3o social (nome empresarial)&#39;. */
    public var razaoSocial: String?
    /** Apresenta o nome fantasia da empresa. */
    public var nomeFantasia: String?
    /** N\u00FAmero do Cadastro Nacional de Pessoa Juridica (CNPJ) */
    public var cnpj: String?
    /** N\u00FAmero da Inscri\u00E7\u00E3o Estadual (IE). */
    public var inscricaoEstadual: String?
    /** Data de abertura da empresa, essa data deve ser informada no formato: aaaa-MM-dd. */
    public var dataAberturaEmpresa: String?
    /** Id da origem comercial */
    public var idOrigemComercial: Int?
    /** Id do produto */
    public var idProduto: Int?
    /** N\u00FAmero da ag\u00EAncia. */
    public var numeroAgencia: Int?
    /** N\u00FAmero da conta corrente. */
    public var numeroContaCorrente: String?
    /** Email da empresa */
    public var email: String?
    /** Dia vencimento */
    public var diaVencimento: Int?
    /** Nome que deve ser impresso no cart\u00E3o */
    public var nomeImpresso: String?
    /** Apresenta o valor da renda compravada */
    public var valorRenda: Double?
    /** Indica o canal pelo qual o cadastro do cliente foi realizado */
    public var canalEntrada: String?
    /** Indica o valor da pontua\u00E7\u00E3o atribuido ao cliente (caso n\u00E3o informado ser\u00E1 atribuido o valor = 0) */
    public var valorPontuacao: Int?
    /** Apresenta os telefones da empresa */
    public var telefones: [TelefonePessoaAprovadaPersist]?
    /** Pode ser informado os seguintes tipos de endere\u00E7o: Residencial, Comercial, e Outros */
    public var enderecos: [EnderecoAprovadoPersist]?
    /** Apresenta os dados dos s\u00F3cios da empresa, caso exista */
    public var socios: [PessoaPersist]?
    /** Apresenta os dados das refer\u00EAncias comerciais */
    public var referenciasComerciais: [RefenciaComercialAprovadoPersist]?
    /** Valor do Limite Global */
    public var limiteGlobal: Double?
    /** Valor m\u00E1ximo do limite de cr\u00E9dito para realizar transa\u00E7\u00F5es */
    public var limiteMaximo: Double?
    /** Valor do limite de cr\u00E9dito acumulado da soma das parcelas das compras */
    public var limiteParcelas: Double?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["razaoSocial"] = self.razaoSocial
        nillableDictionary["nomeFantasia"] = self.nomeFantasia
        nillableDictionary["cnpj"] = self.cnpj
        nillableDictionary["inscricaoEstadual"] = self.inscricaoEstadual
        nillableDictionary["dataAberturaEmpresa"] = self.dataAberturaEmpresa
        nillableDictionary["idOrigemComercial"] = self.idOrigemComercial
        nillableDictionary["idProduto"] = self.idProduto
        nillableDictionary["numeroAgencia"] = self.numeroAgencia
        nillableDictionary["numeroContaCorrente"] = self.numeroContaCorrente
        nillableDictionary["email"] = self.email
        nillableDictionary["diaVencimento"] = self.diaVencimento
        nillableDictionary["nomeImpresso"] = self.nomeImpresso
        nillableDictionary["valorRenda"] = self.valorRenda
        nillableDictionary["canalEntrada"] = self.canalEntrada
        nillableDictionary["valorPontuacao"] = self.valorPontuacao
        nillableDictionary["telefones"] = self.telefones?.encodeToJSON()
        nillableDictionary["enderecos"] = self.enderecos?.encodeToJSON()
        nillableDictionary["socios"] = self.socios?.encodeToJSON()
        nillableDictionary["referenciasComerciais"] = self.referenciasComerciais?.encodeToJSON()
        nillableDictionary["limiteGlobal"] = self.limiteGlobal
        nillableDictionary["limiteMaximo"] = self.limiteMaximo
        nillableDictionary["limiteParcelas"] = self.limiteParcelas
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
