//
// PessoaResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Pessoa */
public class PessoaResponse: JSONEncodable {

    /** C\u00F3digo de Identifica\u00E7\u00E3o da Pessoa (id). */
    public var id: Int?
    /** Apresenta o &#39;Nome Completo da PF&#39; ou o &#39;Nome Completo da Raz\u00E3o Social (Nome Empresarial)&#39;. */
    public var nome: String?
    /** C\u00F3digo de identifica\u00E7\u00E3o do tipo da Pessoa, sendo: (\&quot;PF\&quot;: Pessoa F\u00EDsica), (\&quot;PJ\&quot;: Pessoa Jur\u00EDdica). */
    public var tipo: String?
    /** N\u00FAmero do CPF, quando PF. */
    public var cpf: String?
    /** N\u00FAmero do CNPJ, quando PJ. */
    public var cnpj: String?
    /** Data de Nascimento da Pessoa, quando PF, ou a Data de Abertura da Empresa, quando PJ. */
    public var dataNascimento: String?
    /** N\u00FAmero da Identidade */
    public var numeroIdentidade: String?
    /** Org\u00E3o expedidor do RG. */
    public var orgaoExpedidorIdentidade: String?
    /** C\u00F3digo de identifica\u00E7\u00E3o do sexo da Pessoa, quando PF, sendo: (\&quot;M\&quot;: Masculino), (\&quot;F\&quot;: Feminino), (\&quot;O\&quot;: Outro), (\&quot;N\&quot;: N\u00E3o Especificado). */
    public var sexo: String?
    /** Sigla da Unidade Federativa de onde foi expedido a Identidade */
    public var unidadeFederativaIdentidade: String?
    /** Data emiss\u00E3o da identidade no formato aaaa-MM-dd */
    public var dataEmissaoIdentidade: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["nome"] = self.nome
        nillableDictionary["tipo"] = self.tipo
        nillableDictionary["cpf"] = self.cpf
        nillableDictionary["cnpj"] = self.cnpj
        nillableDictionary["dataNascimento"] = self.dataNascimento
        nillableDictionary["numeroIdentidade"] = self.numeroIdentidade
        nillableDictionary["orgaoExpedidorIdentidade"] = self.orgaoExpedidorIdentidade
        nillableDictionary["sexo"] = self.sexo
        nillableDictionary["unidadeFederativaIdentidade"] = self.unidadeFederativaIdentidade
        nillableDictionary["dataEmissaoIdentidade"] = self.dataEmissaoIdentidade
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
