//
// PlanoParcelamentoResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** {{{plano_parcelamento_response_description}}} */
public class PlanoParcelamentoResponse: JSONEncodable {

    /** {{{plano_parcelamento_response_id_value}}} */
    public var id: Int?
    /** {{{plano_parcelamento_response_data_fechamento_fatura_value}}} */
    public var dataFechamentoFatura: String?
    /** {{{plano_parcelamento_response_data_vencimento_padrao_value}}} */
    public var dataVencimentoPadrao: String?
    /** {{{plano_parcelamento_response_valor_total_fatura_value}}} */
    public var valorTotalFatura: Double?
    /** {{{plano_parcelamento_response_quantidade_parcelas_value}}} */
    public var quantidadeParcelas: Int?
    /** {{{plano_parcelamento_response_valor_parcela_value}}} */
    public var valorParcela: Double?
    /** {{{plano_parcelamento_response_valor_entrada_value}}} */
    public var valorEntrada: Double?
    /** {{{plano_parcelamento_response_taxa_refinanciamento_value}}} */
    public var taxaRefinanciamento: Double?
    /** {{{plano_parcelamento_response_custo_efetivo_total_value}}} */
    public var custoEfetivoTotal: Double?
    /** {{{plano_parcelamento_response_valor_total_refinanciamento_value}}} */
    public var valorTotalRefinanciamento: Double?
    /** {{{plano_parcelamento_response_valor_i_o_f_value}}} */
    public var valorIOF: Double?
    /** {{{plano_parcelamento_response_valor_t_a_c_value}}} */
    public var valorTAC: Double?
    /** {{{plano_parcelamento_response_status_adesao_value}}} */
    public var statusAdesao: Int?
    /** {{{plano_parcelamento_response_data_inclusao_value}}} */
    public var dataInclusao: String?
    /** {{{plano_parcelamento_response_data_processamento_adesao_value}}} */
    public var dataProcessamentoAdesao: String?
    /** {{{plano_parcelamento_response_id_conta_value}}} */
    public var idConta: Int?
    /** {{{plano_parcelamento_response_id_servico_tipo_value}}} */
    public var idServicoTipo: Int?
    /** {{{plano_parcelamento_response_descricao_servico_tipo_value}}} */
    public var descricaoServicoTipo: String?
    /** {{{plano_parcelamento_response_com_entrada_value}}} */
    public var comEntrada: Bool?
    /** {{{plano_parcelamento_response_nome_campanha_value}}} */
    public var nomeCampanha: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["dataFechamentoFatura"] = self.dataFechamentoFatura
        nillableDictionary["dataVencimentoPadrao"] = self.dataVencimentoPadrao
        nillableDictionary["valorTotalFatura"] = self.valorTotalFatura
        nillableDictionary["quantidadeParcelas"] = self.quantidadeParcelas
        nillableDictionary["valorParcela"] = self.valorParcela
        nillableDictionary["valorEntrada"] = self.valorEntrada
        nillableDictionary["taxaRefinanciamento"] = self.taxaRefinanciamento
        nillableDictionary["custoEfetivoTotal"] = self.custoEfetivoTotal
        nillableDictionary["valorTotalRefinanciamento"] = self.valorTotalRefinanciamento
        nillableDictionary["valorIOF"] = self.valorIOF
        nillableDictionary["valorTAC"] = self.valorTAC
        nillableDictionary["statusAdesao"] = self.statusAdesao
        nillableDictionary["dataInclusao"] = self.dataInclusao
        nillableDictionary["dataProcessamentoAdesao"] = self.dataProcessamentoAdesao
        nillableDictionary["idConta"] = self.idConta
        nillableDictionary["idServicoTipo"] = self.idServicoTipo
        nillableDictionary["descricaoServicoTipo"] = self.descricaoServicoTipo
        nillableDictionary["comEntrada"] = self.comEntrada
        nillableDictionary["nomeCampanha"] = self.nomeCampanha
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
