//
// PlanoParcelamentoTransferenciaCreditoContaBancariaRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Transfer\u00C3\u00AAncia cr\u00C3\u00A9dito conta banc\u00C3\u00A1ria request */
public class PlanoParcelamentoTransferenciaCreditoContaBancariaRequest: JSONEncodable {

    /** C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o do cart\u00C3\u00A3o. */
    public var idCartao: Int?
    /** Valor da transa\u00C3\u00A7\u00C3\u00A3o com duas casas decimais para os centavos. */
    public var valorTransacao: Double?
    /** Representa o N\u00C3\u00BAmero de Meses concedido como car\u00C3\u00AAncia. */
    public var numeroMesesCarencia: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["idCartao"] = self.idCartao
        nillableDictionary["valorTransacao"] = self.valorTransacao
        nillableDictionary["numeroMesesCarencia"] = self.numeroMesesCarencia
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
