//
// PushFCMEGCM.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Objeto Notifica\u00C3\u00A7\u00C3\u00A3o Push FCM e GCM */
public class PushFCMEGCM: JSONEncodable {

    public enum Evento: String { 
        case RiscoFraude = "RISCO_FRAUDE"
        case Outros = "OUTROS"
    }
    
    /** C\u00C3\u00B3digo identificado da pessoa */
    public var idPessoa: Int?
    /** C\u00C3\u00B3digo identificador da conta */
    public var idConta: Int?
    /** Apresenta o token do dispositivo que dever\u00C3\u00A1 receber o push. */
    public var tokenDispositivo: String?
    /** Apresenta o token da sua aplica\u00C3\u00A7\u00C3\u00A3o Android gerada pela Google. */
    public var tokenServidor: String?
    /** Apresenta o t\u00C3\u00ADtulo da notifica\u00C3\u00A7\u00C3\u00A3o. */
    public var titulo: String?
    /** Apresenta o texto da notifica\u00C3\u00A7\u00C3\u00A3o a ser enviado. */
    public var conteudo: String?
    /** Apresenta o evento a qual pertence a notifica\u00C3\u00A7\u00C3\u00A3o */
    public var evento: Evento?
    /** Apresenta o nome do icone a ser apresentado no push. */
    public var icone: String?
    /** Apresenta o cor do icone a ser apresentado no push */
    public var som: String?
    /** Apresenta a cor do icone da notifica\u00C3\u00A7\u00C3\u00A3o. Essa cor dever\u00C3\u00A1 ser informada no formato RGB Ex. #000000. */
    public var cor: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["idPessoa"] = self.idPessoa
        nillableDictionary["idConta"] = self.idConta
        nillableDictionary["tokenDispositivo"] = self.tokenDispositivo
        nillableDictionary["tokenServidor"] = self.tokenServidor
        nillableDictionary["titulo"] = self.titulo
        nillableDictionary["conteudo"] = self.conteudo
        nillableDictionary["evento"] = self.evento?.rawValue
        nillableDictionary["icone"] = self.icone
        nillableDictionary["som"] = self.som
        nillableDictionary["cor"] = self.cor
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
