//
// TaxaAntecipacaoRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** {{{taxa_antecipacao_request_description}}} */
public class TaxaAntecipacaoRequest: JSONEncodable {

    public enum TipoTransacao: String { 
        case OnUs = "ON_US"
        case OffUs = "OFF_US"
    }
    
    /** {{{taxa_antecipacao_request_tipo_transacao_value}}} */
    public var tipoTransacao: TipoTransacao?
    /** {{{taxa_antecipacao_request_valor_taxa_value}}} */
    public var valorTaxa: Double?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["tipoTransacao"] = self.tipoTransacao?.rawValue
        nillableDictionary["valorTaxa"] = self.valorTaxa
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
