//
// TipoBoletoResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Fatura */
public class TipoBoletoResponse: JSONEncodable {

    /** C\u00F3digo identificador do tipo de boleto. */
    public var id: Int?
    /** Descri\u00E7\u00E3o do tipo de boleto. */
    public var descricao: String?
    /** C\u00F3digo identificador do banco. */
    public var banco: Int?
    /** Faixa permitida para cria\u00E7\u00E3o do nosso n\u00FAmero. */
    public var faixaNossoNumero: Int?
    /** N\u00FAmero minimo para o nosso n\u00FAmero. */
    public var minNossoNumero: Double?
    /** N\u00FAmero m\u00E1ximo para o nosso n\u00FAmero. */
    public var maxNossoNumero: Double?
    /** Tamanho do nosso n\u00FAmero. */
    public var tamNossoNumero: Int?
    /** \u00DAltimo nosso n\u00FAmero utilizado. */
    public var ultimoNossoNumero: Double?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["descricao"] = self.descricao
        nillableDictionary["banco"] = self.banco
        nillableDictionary["faixaNossoNumero"] = self.faixaNossoNumero
        nillableDictionary["minNossoNumero"] = self.minNossoNumero
        nillableDictionary["maxNossoNumero"] = self.maxNossoNumero
        nillableDictionary["tamNossoNumero"] = self.tamNossoNumero
        nillableDictionary["ultimoNossoNumero"] = self.ultimoNossoNumero
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
