//
// TipoOperacaoResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** {{{tipo_operacao_response_description}}} */
public class TipoOperacaoResponse: JSONEncodable {

    /** {{{tipo_operacao_response_id_value}}} */
    public var id: Int?
    /** {{{tipo_operacao_response_tipo_operacao_value}}} */
    public var tipoOperacao: String?
    /** {{{tipo_operacao_response_nome_value}}} */
    public var nome: String?
    /** {{{tipo_operacao_response_descricao_value}}} */
    public var descricao: String?
    /** {{{tipo_operacao_response_excedente_permitido_value}}} */
    public var excedentePermitido: Double?
    /** {{{tipo_operacao_response_tipo_excedente_permitido_value}}} */
    public var tipoExcedentePermitido: String?
    /** {{{tipo_operacao_response_valor_minimo_value}}} */
    public var valorMinimo: Double?
    /** {{{tipo_operacao_response_valor_maximo_value}}} */
    public var valorMaximo: Double?
    /** {{{tipo_operacao_response_valor_t_a_c_value}}} */
    public var valorTAC: Double?
    /** {{{tipo_operacao_response_flag_tira_tac_value}}} */
    public var flagTiraTac: Int?
    /** {{{tipo_operacao_response_id_produto_value}}} */
    public var idProduto: Int?
    /** {{{tipo_operacao_response_id_estabelecimento_value}}} */
    public var idEstabelecimento: Int?
    /** {{{tipo_operacao_response_tarifa_value}}} */
    public var tarifa: Double?
    /** {{{tipo_operacao_response_remuneracao_emissor_value}}} */
    public var remuneracaoEmissor: Double?
    /** {{{tipo_operacao_response_plano_maximo_value}}} */
    public var planoMaximo: Int?
    /** {{{tipo_operacao_response_plano_minimo_value}}} */
    public var planoMinimo: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["tipoOperacao"] = self.tipoOperacao
        nillableDictionary["nome"] = self.nome
        nillableDictionary["descricao"] = self.descricao
        nillableDictionary["excedentePermitido"] = self.excedentePermitido
        nillableDictionary["tipoExcedentePermitido"] = self.tipoExcedentePermitido
        nillableDictionary["valorMinimo"] = self.valorMinimo
        nillableDictionary["valorMaximo"] = self.valorMaximo
        nillableDictionary["valorTAC"] = self.valorTAC
        nillableDictionary["flagTiraTac"] = self.flagTiraTac
        nillableDictionary["idProduto"] = self.idProduto
        nillableDictionary["idEstabelecimento"] = self.idEstabelecimento
        nillableDictionary["tarifa"] = self.tarifa
        nillableDictionary["remuneracaoEmissor"] = self.remuneracaoEmissor
        nillableDictionary["planoMaximo"] = self.planoMaximo
        nillableDictionary["planoMinimo"] = self.planoMinimo
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
