//
// TipoOportunidadeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Representa\u00E7\u00E3o da resposta do recurso TipoOportunidade */
public class TipoOportunidadeResponse: JSONEncodable {

    /** C\u00F3digo identificador do TipoOportunidade */
    public var id: Int?
    /** Descricao do TipoOportunidade */
    public var descricao: String?
    /** Flag que representa se o tipo oportunidade est\u00E1 ativo */
    public var flagAtivo: Bool?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["descricao"] = self.descricao
        nillableDictionary["flagAtivo"] = self.flagAtivo
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
