//
// TokenResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Representa\u00C3\u00A7\u00C3\u00A3o do recurso token */
public class TokenResponse: JSONEncodable {

    public enum Status: String { 
        case Active = "ACTIVE"
        case Revoked = "REVOKED"
        case Deleted = "DELETED"
    }
    
    /** C\u00C3\u00B3digo identificador do token */
    public var id: Int?
    /** Token */
    public var token: String?
    /** C\u00C3\u00B3digo identificador da base */
    public var base: Int?
    /** Owner do token */
    public var owner: String?
    /** Status do token */
    public var status: Status?
    /** Descri\u00C3\u00A7\u00C3\u00A3o de quem criou o token */
    public var criadoPor: String?
    /** Data de cria\u00C3\u00A7\u00C3\u00A3o do token */
    public var dataCriacao: NSDate?
    /** Descri\u00C3\u00A7\u00C3\u00A3o de quem alterou o token */
    public var alteradoPor: String?
    /** Data de modifica\u00C3\u00A7\u00C3\u00A3o do token */
    public var dataModificacao: NSDate?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["token"] = self.token
        nillableDictionary["base"] = self.base
        nillableDictionary["owner"] = self.owner
        nillableDictionary["status"] = self.status?.rawValue
        nillableDictionary["criadoPor"] = self.criadoPor
        nillableDictionary["dataCriacao"] = self.dataCriacao?.encodeToJSON()
        nillableDictionary["alteradoPor"] = self.alteradoPor
        nillableDictionary["dataModificacao"] = self.dataModificacao?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
