//
// TransferenciaCreditoContaBancariaPersistValue.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** {{{transferencia_credito_conta_bancaria_persist_description}}} */
public class TransferenciaCreditoContaBancariaPersistValue: JSONEncodable {

    /** {{{transferencia_credito_conta_bancaria_persist_nsu_origem_value}}} */
    public var nsuOrigem: Int?
    /** {{{transferencia_credito_conta_bancaria_persist_id_cartao_value}}} */
    public var idCartao: Int?
    /** {{{transferencia_credito_conta_bancaria_persist_id_conta_bancaria_value}}} */
    public var idContaBancaria: Int?
    /** {{{transferencia_credito_conta_bancaria_persist_valor_value}}} */
    public var valor: Double?
    /** {{{transferencia_credito_conta_bancaria_persist_numero_parcelas_value}}} */
    public var numeroParcelas: Int?
    /** {{{transferencia_credito_conta_bancaria_persist_numero_meses_carencia_value}}} */
    public var numeroMesesCarencia: Int?
    /** {{{transferencia_credito_conta_bancaria_persist_data_hora_terminal_value}}} */
    public var dataHoraTerminal: String?
    /** {{{transferencia_credito_conta_bancaria_persist_terminal_requisitante_value}}} */
    public var terminalRequisitante: String?
    /** {{{transferencia_credito_conta_bancaria_persist_numero_estabelecimento_value}}} */
    public var numeroEstabelecimento: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["nsuOrigem"] = self.nsuOrigem
        nillableDictionary["idCartao"] = self.idCartao
        nillableDictionary["idContaBancaria"] = self.idContaBancaria
        nillableDictionary["valor"] = self.valor
        nillableDictionary["numeroParcelas"] = self.numeroParcelas
        nillableDictionary["numeroMesesCarencia"] = self.numeroMesesCarencia
        nillableDictionary["dataHoraTerminal"] = self.dataHoraTerminal
        nillableDictionary["terminalRequisitante"] = self.terminalRequisitante
        nillableDictionary["numeroEstabelecimento"] = self.numeroEstabelecimento
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
