//
// TransacaoPayQueryRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Representa\u00E7\u00E3o da requisi\u00E7\u00E3o do recurso de consultar conta */
public class TransacaoPayQueryRequest: JSONEncodable {

    /** Numero do cartao (criptografado) */
    public var numeroCartao: String?
    /** Id do cart\u00E3o */
    public var idCartao: Int?
    /** Origem */
    public var origem: String?
    /** Tipo de ordena\u00E7\u00E3o dos registros. */
    public var sort: [String]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["numeroCartao"] = self.numeroCartao
        nillableDictionary["idCartao"] = self.idCartao
        nillableDictionary["origem"] = self.origem
        nillableDictionary["sort"] = self.sort?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
