//
// TransferenciaCreditoContaBancariaListaResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Listagem de Transfer\u00C3\u00AAncia de cr\u00C3\u00A9dito para contas banc\u00C3\u00A1rias */
public class TransferenciaCreditoContaBancariaListaResponse: JSONEncodable {

    /** C\u00C3\u00B3digo de identifica\u00C3\u00A7\u00C3\u00A3o da transferencia. */
    public var idTransferencia: Int?
    /** Valor da transfer\u00C3\u00AAncia. */
    public var valorCompra: Double?
    /** Valor da transfer\u00C3\u00AAncia acrescido do valor da tarifa de saque se houver tarifa de saque. */
    public var valorContrato: Double?
    /** Data da transfer\u00C3\u00AAncia. */
    public var dataCompra: String?
    /** Status Processamento. */
    public var statusProcessamento: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["idTransferencia"] = self.idTransferencia
        nillableDictionary["valorCompra"] = self.valorCompra
        nillableDictionary["valorContrato"] = self.valorContrato
        nillableDictionary["dataCompra"] = self.dataCompra
        nillableDictionary["statusProcessamento"] = self.statusProcessamento
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
