//
// TransferenciaCreditoContaBancariaResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** {{{transferencia_credito_conta_bancaria_response_description}}} */
public class TransferenciaCreditoContaBancariaResponse: JSONEncodable {

    /** {{{transferencia_credito_conta_bancaria_response_id_transferencia_value}}} */
    public var idTransferencia: Int?
    /** {{{transferencia_credito_conta_bancaria_response_valor_c_e_t_value}}} */
    public var valorCET: Double?
    /** {{{transferencia_credito_conta_bancaria_response_id_autorizacao_value}}} */
    public var idAutorizacao: Int?
    /** {{{transferencia_credito_conta_bancaria_response_codigo_autorizacao_value}}} */
    public var codigoAutorizacao: String?
    /** {{{transferencia_credito_conta_bancaria_response_nsu_origem_value}}} */
    public var nsuOrigem: Int?
    /** {{{transferencia_credito_conta_bancaria_response_id_conta_value}}} */
    public var idConta: Int?
    /** {{{transferencia_credito_conta_bancaria_response_id_cartao_value}}} */
    public var idCartao: Int?
    /** {{{transferencia_credito_conta_bancaria_response_id_operacao_value}}} */
    public var idOperacao: Int?
    /** {{{transferencia_credito_conta_bancaria_response_valor_compra_value}}} */
    public var valorCompra: Double?
    /** {{{transferencia_credito_conta_bancaria_response_valor_parcela_value}}} */
    public var valorParcela: Double?
    /** {{{transferencia_credito_conta_bancaria_response_valor_contrato_value}}} */
    public var valorContrato: Double?
    /** {{{transferencia_credito_conta_bancaria_response_numero_parcelas_value}}} */
    public var numeroParcelas: Int?
    /** {{{transferencia_credito_conta_bancaria_response_valor_i_o_f_value}}} */
    public var valorIOF: Double?
    /** {{{transferencia_credito_conta_bancaria_response_valor_t_a_c_value}}} */
    public var valorTAC: Double?
    /** {{{transferencia_credito_conta_bancaria_response_valor_taxa_saque_value}}} */
    public var valorTaxaSaque: Double?
    /** {{{transferencia_credito_conta_bancaria_response_taxa_juros_value}}} */
    public var taxaJuros: Double?
    /** {{{transferencia_credito_conta_bancaria_response_data_compra_value}}} */
    public var dataCompra: String?
    /** {{{transferencia_credito_conta_bancaria_response_data_movimento_value}}} */
    public var dataMovimento: String?
    /** {{{transferencia_credito_conta_bancaria_response_data_vencimento_real_value}}} */
    public var dataVencimentoReal: String?
    /** {{{transferencia_credito_conta_bancaria_response_data_vencimento_padrao_value}}} */
    public var dataVencimentoPadrao: String?
    /** {{{transferencia_credito_conta_bancaria_response_data_autorizacao_value}}} */
    public var dataAutorizacao: String?
    /** {{{transferencia_credito_conta_bancaria_response_banco_value}}} */
    public var banco: Int?
    /** {{{transferencia_credito_conta_bancaria_response_numero_agencia_value}}} */
    public var numeroAgencia: String?
    /** {{{transferencia_credito_conta_bancaria_response_digito_agencia_value}}} */
    public var digitoAgencia: String?
    /** {{{transferencia_credito_conta_bancaria_response_numero_conta_value}}} */
    public var numeroConta: String?
    /** {{{transferencia_credito_conta_bancaria_response_digito_conta_value}}} */
    public var digitoConta: String?
    /** {{{transferencia_credito_conta_bancaria_response_flag_conta_poupanca_value}}} */
    public var flagContaPoupanca: Bool?
    /** {{{transferencia_credito_conta_bancaria_response_documento_favorecido_value}}} */
    public var documentoFavorecido: String?
    /** {{{transferencia_credito_conta_bancaria_response_nome_favorecido_value}}} */
    public var nomeFavorecido: String?
    /** {{{transferencia_credito_conta_bancaria_response_status_value}}} */
    public var status: String?
    /** {{{transferencia_credito_conta_bancaria_response_status_processamento_value}}} */
    public var statusProcessamento: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["idTransferencia"] = self.idTransferencia
        nillableDictionary["valorCET"] = self.valorCET
        nillableDictionary["idAutorizacao"] = self.idAutorizacao
        nillableDictionary["codigoAutorizacao"] = self.codigoAutorizacao
        nillableDictionary["nsuOrigem"] = self.nsuOrigem
        nillableDictionary["idConta"] = self.idConta
        nillableDictionary["idCartao"] = self.idCartao
        nillableDictionary["idOperacao"] = self.idOperacao
        nillableDictionary["valorCompra"] = self.valorCompra
        nillableDictionary["valorParcela"] = self.valorParcela
        nillableDictionary["valorContrato"] = self.valorContrato
        nillableDictionary["numeroParcelas"] = self.numeroParcelas
        nillableDictionary["valorIOF"] = self.valorIOF
        nillableDictionary["valorTAC"] = self.valorTAC
        nillableDictionary["valorTaxaSaque"] = self.valorTaxaSaque
        nillableDictionary["taxaJuros"] = self.taxaJuros
        nillableDictionary["dataCompra"] = self.dataCompra
        nillableDictionary["dataMovimento"] = self.dataMovimento
        nillableDictionary["dataVencimentoReal"] = self.dataVencimentoReal
        nillableDictionary["dataVencimentoPadrao"] = self.dataVencimentoPadrao
        nillableDictionary["dataAutorizacao"] = self.dataAutorizacao
        nillableDictionary["banco"] = self.banco
        nillableDictionary["numeroAgencia"] = self.numeroAgencia
        nillableDictionary["digitoAgencia"] = self.digitoAgencia
        nillableDictionary["numeroConta"] = self.numeroConta
        nillableDictionary["digitoConta"] = self.digitoConta
        nillableDictionary["flagContaPoupanca"] = self.flagContaPoupanca
        nillableDictionary["documentoFavorecido"] = self.documentoFavorecido
        nillableDictionary["nomeFavorecido"] = self.nomeFavorecido
        nillableDictionary["status"] = self.status
        nillableDictionary["statusProcessamento"] = self.statusProcessamento
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
