//
// VinculoCartoesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** {{{vincular_cartoes_response_description}}} */
public class VinculoCartoesResponse: JSONEncodable {

    /** {{{vincular_cartoes_response_id_cartao_value}}} */
    public var idCartaoPrincipal: Int?
    /** {{{vincular_cartoes_response_id_cartao_vinculado_value}}} */
    public var idCartaoVinculado: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["idCartaoPrincipal"] = self.idCartaoPrincipal
        nillableDictionary["idCartaoVinculado"] = self.idCartaoVinculado
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
