//
// WebHook.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Representa\u00C3\u00A7\u00C3\u00A3o do recurso WebHook */
public class WebHook: JSONEncodable {

    public enum Evento: String { 
        case RiscoFraude = "RISCO_FRAUDE"
        case Outros = "OUTROS"
    }
    
    public enum Metodo: String { 
        case Get = "GET"
        case Post = "POST"
        case Put = "PUT"
        case Delete = "DELETE"
    }
    
    /** Evento a ser chamado pelo WebHook */
    public var evento: Evento?
    /** Id do WebHook */
    public var id: Int?
    /** M\u00C3\u00A9todo que a ser chamado pelo WebHook */
    public var metodo: Metodo?
    /** URL que a ser consumida pelo WebHook */
    public var url: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["evento"] = self.evento?.rawValue
        nillableDictionary["id"] = self.id
        nillableDictionary["metodo"] = self.metodo?.rawValue
        nillableDictionary["url"] = self.url
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
